### ISSUE TITLE
Need help to add understand how to add corewlan

### ISSUE THREAD

**Issue by tejaskumark** [PumpkinSeed/macdriver2#1]
@PumpkinSeed Hope you are fine. I wanted to interact with CoreWLAN module for Mac OS from golang, and came across this macdriver. I see that you have added support for bluetooth module, so I was wondering that,
- Is corebluetooth module working fine with mac ?
- Is it possible to guide me through the process for adding corewlan module?
Any help appreciated. Thanks.

**Comment by PumpkinSeed** [comment]
Hi, 

Actually every attempt what we tried to make the Go bindings compatible with corebluetooth is failed so we let it go. You maybe can find something in the original repository: https://github.com/progrium/macdriver
